baseURL = 'https://ranakizil.github.io/'
locale = 'en-us'
title = "rana's blog"
theme = 'hugo-book'

[params]
  BookTitle = "rana's blog"
  BookSearch = false
  BookToC = false
  BookTheme = 'light'
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
